ToDo/urls.py
from django.contrib import admin
from django.urls import path, include
from ToDo.settings import DEBUG


urlpatterns = [
    path("admin/", admin.site.urls),
    path("todo/", include("todo_list.urls", namespace="todo_list")),
]

if DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]

todo_list/urls.py
from django.urls import path
from todo_list import views

app_name = "todo_list"

urlpatterns = [
    path("login", views.UserLoginView.as_view(), name="index"),
    path("todo", views.TodoView.as_view(), name="todo"),
    path("signup", views.UserSignUpView.as_view(), name="signup"),
    path("logout", views.logout, name="logout"),
    path("add_task", views.TaskAddView.as_view(), name="add_task"),
    path("remove_task/<int:task_id>/", views.TaskDeleteView.as_view(), name="remove_task"),
]

todo_list/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class Users(AbstractUser):

    class Meta:
        db_table = "user"
        verbose_name = "user"
        verbose_name_plural = "users"

    def __str__(self) -> str:
        return f"{self.username}"


class Tasks(models.Model):
    
    task = models.CharField(max_length=150)
    priority = models.PositiveSmallIntegerField(default=1, db_index=True)
    user = models.ForeignKey(Users, on_delete=models.CASCADE, related_name="Users")

    def __str__(self) -> str:
        return f"{self.task} - {self.priority}"

    class Meta:
        db_table = "task"
        verbose_name = "task"
        verbose_name_plural = "tasks"
        ordering = ("-priority",)

todo_list/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from todo_list.models import Tasks, Users


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(
        required=True,
        label="Username",
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                "placeholder": "Enter your username",
                "class": "form-control",
                "name": "username",
            }
        ),
    )
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "placeholder": "Enter your password",
                "class": "form-control",
                "name": "password",
            }
        ),
    )

    class Meta:
        model = Users
        fields = ["username", "password"]


class UserSignupForm(UserCreationForm):
    class Meta:
        model = Users
        fields = (
            "username",
            "password1",
            "password2",
        )

    username = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class NewTaskForm(forms.Form):
    class Meta:
        model = Tasks
        fields = ["task", "priority"]

    task = forms.CharField(
        label="Task",
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "Enter new task", "name": "task"}),
    )
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

todo_list/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, FormView
from todo_list.forms import NewTaskForm, UserLoginForm, UserSignupForm
from todo_list.models import Users, Tasks


# Create your views here.


class TodoView(TemplateView):
    
    template_name = "todo_list/todo.html"

    def get(self, request, *args, **kwargs) -> HttpResponse:
        if not request.user.is_authenticated:
            return redirect(reverse('todo_list:index'))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict:
        
        context = super().get_context_data(**kwargs)
        user_id = self.request.user.id
        tasks = Tasks.objects.filter(user_id=user_id)
        context['tasks'] = tasks
        
        return context


class UserLoginView(LoginView):

    template_name = 'todo_list/index.html'
    form_class = UserLoginForm
    next_page = reverse_lazy('todo_list:todo')



class UserSignUpView(CreateView):
    template_name = 'todo_list/signup.html'
    form_class = UserSignupForm
    success_url = reverse_lazy('todo_list:todo')

    def form_valid(self, form):
        user = form.instance

        if user:
            form.save()
            auth.login(self.request, user)
            return redirect(self.success_url)


@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse("todo_list:index"))

class TaskAddView(FormView):
    template_name = 'todo_list/add_task.html'
    form_class = NewTaskForm

    def get(self, request) -> HttpResponse:
        if not self.request.user.is_authenticated:
            return redirect(reverse('todo_list:index'))
        form = NewTaskForm()

        return render(self.request, "todo_list/addtask.html", {"form": form})

    def form_valid(self, form):
        form = form.cleaned_data
        object = Tasks()
        object.task = form["task"]
        object.priority = form["priority"]
        object.user_id = (
            Users.objects.filter(username=self.request.user)
            .values_list("id", flat=True)
            .first()
        )
        object.save()
        return redirect(reverse("todo_list:todo"))
    

class TaskDeleteView(TemplateView):
    
    def get(self, request, task_id):
        task = Tasks.objects.get(id=task_id)
        task.delete()

        return redirect(self.request.META["HTTP_REFERER"])

todo_list/templates/todo_list/addtask.html
{% extends "todo_list/layout.html" %}
{% load static %}

{% block head %}
    <title>Add task</title>
    <link rel="stylesheet" href="{% static "todo_list/css/userformsstyles.css" %}">
{% endblock head %}

{% block body %}
    <div id='adder' class='form-check-inline'>
    <div class='row justify-content-center'>
        <h1>Add new task</h1>
        <form action="{% url "todo_list:add_task" %}", method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Add" class='btn btn-dark btn-block'> 
        </form>
    </div>
    </div>
    <script>
        document.body.style.overflow = "hidden";
    </script>
{% endblock body %}

todo_list/templates/todo_list/index.html
{% extends "todo_list/layout.html" %}
{% load static %}

{% block head %}
  <title>Login</title>
  <link rel="stylesheet" href="{% static "todo_list/css/userformsstyles.css" %}">
{% endblock head %}

{% block body %}
<div class='pwelcome'>
  <p>Welcome to ToDo app</p>
</div>
<div class='container-form form-check-inline'>
  <div class='row justify-content-center'>
    <h1>Login</h1>
    <form action="{% url 'todo_list:index' %}" , method="post">
      {% csrf_token %}
      {% if form.non_field_errors %}
      <div class="container mt-4">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
              {{form.non_field_errors}}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
      <div class='mb-3'>
        <label for='{{ form.username.id_for_label }}' class='form-label'>Username</label>
        {{ form.username }}
      </div>
      <div class='mb-3'>
        <label for='{{ form.password.id_for_label }}' class='form-label'>Password</label>
        {{ form.password }}
      </div>
      <button type='submit' class='btn btn-dark btn-block'>Sign in</button>
    </form>
    <a href="">Forgot Password</a>
    <a href="{% url 'todo_list:signup' %}">Signup</a>
  </div>
</div>
<script>
  document.body.style.overflow = "hidden";
</script>
{% endblock body %}

todo_list/templates/todo_list/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block head %}
    {% endblock head %}
</head>

<body>
    {% block body %}
    {% endblock body %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body >
</html>

todo_list/templates/todo_list/signup.html
{% extends "todo_list/layout.html" %}
{% load static %}

{% block head %}
    <title>Signup</title>
    <link rel="stylesheet" href="{% static "todo_list/css/userformsstyles.css" %}">
{% endblock head %}

{% block body %}
<div class='pwelcome'>
  <p>Welcome to ToDo app</p>
</div>
    <div class='container-form form-check-inline'>
      
        <div class='form-app'>
            <h1>Signup</h1>
      <form action="{% url 'todo_list:signup' %}" method="post">
        {% csrf_token %}
        <div class='mb-3'>
          <label for='id_username' class='form-label'>Username</label>
          <p><input type="text", name="username", placeholder="Username", class='form-control', id='id_username', value="{% if form.username.value %}{{form.username.value}}{% endif %}", required></p>
          {% if form.username.errors %}
          <div class='alert alert-danger alert-dismissible fade show'>{{form.username.errors}}</div>
          {% endif %}
        </div>
        <div class='mb-3'>
          <label for='id_password1' class='form-label'>Password</label>
          <p><input type="password", name="password1", placeholder="Password", class='form-control', id='id_password1', value="{% if form.password1.value %}{{form.password1.value}}{% endif %}", required></p>
          {% if form.password1.errors %}
          <div class='alert alert-danger alert-dismissible fade show'>{{form.password1.errors}}</div>
          {% endif %}
        </div>
        <div class='mb-3'>
          <label for='id_password2' class='form-label'>Password confirmation</label>
          <p><input type="password", name="password2", placeholder="Confirm your password", class='form-control', id='id_password2', value="{% if form.password2.value %}{{form.password2.value}}{% endif %}", required></p>
          {% if form.password2.errors %}
          <div class='alert alert-danger alert-dismissible fade show'>{{form.password2.errors}}</div>
          {% endif %}
        </div>
        <button type="submit", class='btn btn-dark btn-block'>Sign up</button>
      </form>
      <span>
        <h5>Already have account? <a href="{% url "todo_list:index" %}">Click here</a></h5>
      </span>
        
      
        </div>
    </div>
{% endblock body %}

todo_list/templates/todo_list/todo.html
{% extends "todo_list/layout.html" %}
{% load static %}

{% block head %}
<title>ToDo</title>
<link rel="stylesheet" href=" {% static 'todo_list/css/footerstyle.css' %} ">
<link rel="stylesheet" href=" {% static 'todo_list/css/styles.css' %} ">
{% comment %} <script type='text/javascript' src="{% static 'todo_list/js/daymoonscript.js' %}"></script> {% endcomment %}
{% endblock head %}

{% block body %}


<header>
  <nav class="navbar navbar-expand-lg bg-dark-subtle custom-shadow">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">ToDo</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_admin or user.is_staff %}
          <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Administration</a>
          {% endif %}
          <a class="nav-link" href="{% url "todo_list:add_task" %}">Add new task</a>
          <a class="nav-link" href="{% url "todo_list:logout" %}">Log Out</a>
        </div>
      </div>
    </div>
  </nav>
</header>
<section>
  <div class="left-chapter">
  </div>
  <div class="content">
    <h1>Tasks</h1>
    {% for task in tasks %}
    <ul>
      <p>
        <li>{{task.task}} - pr. {{task.priority}} <button class='btn btn-dark btn-block'><a href="{% url "todo_list:remove_task" task.id %}" id='del-but'>Done(Delete)</a></button></li>
      </p>
    </ul>
    {% empty %}
    <h2>There's no Tasks</h2>
    {% endfor %}
  </div>
  <div class="right-chapter">
  </div>
</section>
<footer>
  {% comment %} <div id="clrmode">
    <button id='nd'>S/M</button>
  </div> {% endcomment %}
  <div id="cpright">
    CopyRight © ToDo 2025

  </div>
</footer>

{% endblock body %}